/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseProfileIdRouteImport } from './routes/browse.$profileId'
import { Route as BrowseProfileIdIndexRouteImport } from './routes/browse.$profileId.index'
import { Route as BrowseProfileIdSearchRouteImport } from './routes/browse.$profileId.search'
import { Route as BrowseProfileIdMyListRouteImport } from './routes/browse.$profileId.my-list'

const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseProfileIdRoute = BrowseProfileIdRouteImport.update({
  id: '/browse/$profileId',
  path: '/browse/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseProfileIdIndexRoute = BrowseProfileIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrowseProfileIdRoute,
} as any)
const BrowseProfileIdSearchRoute = BrowseProfileIdSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BrowseProfileIdRoute,
} as any)
const BrowseProfileIdMyListRoute = BrowseProfileIdMyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => BrowseProfileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profiles': typeof ProfilesRoute
  '/browse/$profileId': typeof BrowseProfileIdRouteWithChildren
  '/browse/$profileId/my-list': typeof BrowseProfileIdMyListRoute
  '/browse/$profileId/search': typeof BrowseProfileIdSearchRoute
  '/browse/$profileId/': typeof BrowseProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profiles': typeof ProfilesRoute
  '/browse/$profileId/my-list': typeof BrowseProfileIdMyListRoute
  '/browse/$profileId/search': typeof BrowseProfileIdSearchRoute
  '/browse/$profileId': typeof BrowseProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profiles': typeof ProfilesRoute
  '/browse/$profileId': typeof BrowseProfileIdRouteWithChildren
  '/browse/$profileId/my-list': typeof BrowseProfileIdMyListRoute
  '/browse/$profileId/search': typeof BrowseProfileIdSearchRoute
  '/browse/$profileId/': typeof BrowseProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profiles'
    | '/browse/$profileId'
    | '/browse/$profileId/my-list'
    | '/browse/$profileId/search'
    | '/browse/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profiles'
    | '/browse/$profileId/my-list'
    | '/browse/$profileId/search'
    | '/browse/$profileId'
  id:
    | '__root__'
    | '/'
    | '/profiles'
    | '/browse/$profileId'
    | '/browse/$profileId/my-list'
    | '/browse/$profileId/search'
    | '/browse/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfilesRoute: typeof ProfilesRoute
  BrowseProfileIdRoute: typeof BrowseProfileIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$profileId': {
      id: '/browse/$profileId'
      path: '/browse/$profileId'
      fullPath: '/browse/$profileId'
      preLoaderRoute: typeof BrowseProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$profileId/': {
      id: '/browse/$profileId/'
      path: '/'
      fullPath: '/browse/$profileId/'
      preLoaderRoute: typeof BrowseProfileIdIndexRouteImport
      parentRoute: typeof BrowseProfileIdRoute
    }
    '/browse/$profileId/search': {
      id: '/browse/$profileId/search'
      path: '/search'
      fullPath: '/browse/$profileId/search'
      preLoaderRoute: typeof BrowseProfileIdSearchRouteImport
      parentRoute: typeof BrowseProfileIdRoute
    }
    '/browse/$profileId/my-list': {
      id: '/browse/$profileId/my-list'
      path: '/my-list'
      fullPath: '/browse/$profileId/my-list'
      preLoaderRoute: typeof BrowseProfileIdMyListRouteImport
      parentRoute: typeof BrowseProfileIdRoute
    }
  }
}

interface BrowseProfileIdRouteChildren {
  BrowseProfileIdMyListRoute: typeof BrowseProfileIdMyListRoute
  BrowseProfileIdSearchRoute: typeof BrowseProfileIdSearchRoute
  BrowseProfileIdIndexRoute: typeof BrowseProfileIdIndexRoute
}

const BrowseProfileIdRouteChildren: BrowseProfileIdRouteChildren = {
  BrowseProfileIdMyListRoute: BrowseProfileIdMyListRoute,
  BrowseProfileIdSearchRoute: BrowseProfileIdSearchRoute,
  BrowseProfileIdIndexRoute: BrowseProfileIdIndexRoute,
}

const BrowseProfileIdRouteWithChildren = BrowseProfileIdRoute._addFileChildren(
  BrowseProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilesRoute: ProfilesRoute,
  BrowseProfileIdRoute: BrowseProfileIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
